Orderer: &OrdererDefaults
  OrdererType: solo
  Organizations: {}

Application: &ApplicationDefaults
  Organizations: {}

Channel: &ChannelDefaults

Organizations:
  - &Org1
    Name: Org1
    ID: DEFAULT
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp/
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DEFAULT.member')"
      Writers:
        Type: Signature
        Rule: "OR('DEFAULT.member')"
      Admins:
        Type: Signature
        Rule: "OR('DEFAULT.member')"
    AnchorPeers:
      - Host: peer0.org1.example.com
        Port: 7051

Profiles:
  Genesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Org1
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
  Channel:
    Consortium: SampleConsortium
    Application: {}
    # Application:
    #   <<: *ApplicationDefaults
    #   Organizations:
    #     - *Org1
