Application: &ApplicationDefaults
  Organizations: {}
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('PEER.member')"
    Writers:
      Type: Signature
      Rule: "OR('PEER.member')"
    Admins:
      Type: Signature
      Rule: "OR('PEER.member')"

Organizations: &Organizations
  - Name: Org
    ID: ORDERER
    MSPDir: crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ORDERER.member')"
      Writers:
        Type: Signature
        Rule: "OR('ORDERER.member')"
      Admins:
        Type: Signature
        Rule: "OR('ORDERER.member')"
  - Name: Org1
    ID: PEER
    MSPDir: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('PEER.member')"
      Writers:
        Type: Signature
        Rule: "OR('PEER.member')"
      Admins:
        Type: Signature
        Rule: "OR('PEER.member')"
    AnchorPeers:
      - Host: peer0.org1.example.com
        Port: 7051

Channel:
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('PEER.member')"
    Writers:
      Type: Signature
      Rule: "OR('PEER.member')"
    Admins:
      Type: Signature
      Rule: "OR('PEER.member')"

Profiles:
  Genesis:
    Orderer:
      OrdererType: solo
      Organizations: *Organizations
    Application:
      <<: *ApplicationDefaults
      Organizations: *Organizations
    Consortiums:
      SampleConsortium:
        Organizations: *Organizations
  Channel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations: *Organizations
